float *vector(int, int);
float **matrix(int, int, int, int);
double *dvector(int, int);
double **dmatrix(int, int, int, int);
int *ivector(int, int);
int **imatrix(int, int, int, int);
float **submatrix(float **, int, int, int, int, int, int);
void free_vector(float *, int, int);
void free_dvector(double *, int, int);
void free_ivector(int *, int, int);
void free_matrix(float **, int, int, int, int);
void free_dmatrix(double **, int, int, int, int);
void free_imatrix(int **, int, int, int, int);
void free_submatrix(float **, int, int, int, int);
void nrerror(char *);
void lubksb(double **, int, int*, double[]);
float **convert_matrix(float *, int, int, int, int);
void free_convert_matrix(float **, int, int, int, int);